### ISSUE TITLE
Platform independence in tests

### ISSUE THREAD

**Issue by pdvrieze** [mipt-npm/gdml.kt#10]
The test uses a hardcoded path separator, only working on Windows. This patch makes it platform independent.

Btw. there is a typo in the package name.

```
Index: src/jvmTest/kotlin/sicentifik/gdml/BMNTest.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/jvmTest/kotlin/sicentifik/gdml/BMNTest.kt	(revision a8296c66747217dc06d366680ff522c0c5ee6b85)
+++ src/jvmTest/kotlin/sicentifik/gdml/BMNTest.kt	(date 1576593574631)
@@ -36,7 +36,7 @@
     @Test
     fun testRead() {
         val url = URL("https://drive.google.com/open?id=1w5e7fILMN83JGgB8WANJUYm8OW2s0WVO")
-        val file = File("gdml-source\\BM@N.gdml")
+        val file = File("gdml-source${File.separatorChar}BM@N.gdml")
         //val file = File("D:\\Work\\Projects\\gdml.kt\\gdml-source\\cubes.gdml")
         val stream = if(file.exists()){
             file.inputStream()
```

**Comment by altavir** [comment]
Yes, thanks. I hoped to write tests that could be used on JS, but it is not that simple due to file loading procedure and lack of multi-platform resource loaders. I will rewrite tests soon.

What typo? Are you talking about `k` in the end? It is intentional. I am not sure I am hapy with the name, we are discussing a change to `kscience`, `SciKiT` or something like that.

**Comment by altavir** [comment]
By the way, `/` works on Windows, so it could be used everywhere.

**Comment by pdvrieze** [comment]
The typo is "sicentifik" instead of "scientifik" .
Javascript is still not as good as desirable, especially packaging. It seems only flatpack really works properly.

**Comment by altavir** [comment]
Oh, you are correct. Luckily it is only for tests. Thank you very much.
