### ISSUE TITLE
Set default units (length, angle...) when building GDML object

### ISSUE THREAD

**Issue by lobis** [mipt-npm/gdml.kt#21]
It would be useful to choose the default units (mm for length etc.) when building the `Gdml`.

**Comment by altavir** [comment]
A simple option without violating the gdml structure is to add some kind of export options like this:
```kotlin
gdml.encodeToString{
  defaultlUnit = LUnit.MM
}
```
Would it suffice?

**Comment by lobis** [comment]
yes, that is exactly what I wanted.

**Comment by altavir** [comment]
Fixed in `dev`, see https://github.com/mipt-npm/gdml.kt/blob/e01cd969ae621ba4661ef8d51fcb72e0a28efc1e/src/commonMain/kotlin/space/kscience/gdml/GdmlShowCase.kt#L424

**Comment by altavir** [comment]
And default units were wrong after all.  I fixed that as well.

**Comment by lobis** [comment]
Good to know, this will solve the discrepancies between the exported gdml and the renderer I was observing.
