### ISSUE TITLE
Make `name` field optional to simplify syntax

### ISSUE THREAD

**Issue by lobis** [mipt-npm/gdml.kt#23]
When defining geometries I often name my solid/volume the same as the variable that holds the object (e.g. `val foo = solids.box("foo", 1,1,1)`). I am finding myself doing too much "copy and paste", perhaps there can be a default value such as the name of the object (reflection) or in case this is not available some random not in use name.

Also I recommend looking into [https://geant4.web.cern.ch/sites/geant4.web.cern.ch/files/geant4/collaboration/working_groups/geometry/docs/textgeom/textgeom.pdf](url), the Geant4 Text Geometry plain text description (which can be exported to GDML). In this description you can define physical volumes without the need of defining its solid / volumes first. I found this description very useful and user friendly to write simple geometries, perhaps we could integrate some of the best parts of this description.

Text Geometry: Tube physical volumes defined in a single line

```
:VOLU target TUBE 0 50 100 G4_Ge
:PLACE target 1 world R00 0. 0. 0.
```

Example where this happens a lot:
[https://github.com/mipt-npm/gdml.kt/blob/e01cd969ae621ba4661ef8d51fcb72e0a28efc1e/gdml-script/src/test/kotlin/babyIAXO.gdml.kts](url)

**Comment by altavir** [comment]
Done in `0.4.0-dev-1`. It is a breaking change for places where the name is in the first place. See [showcase](https://github.com/mipt-npm/gdml.kt/blob/master/src/commonMain/kotlin/space/kscience/gdml/GdmlShowCase.kt) examples for the reference.
