### ISSUE TITLE
Implement grouping of physical volumes

### ISSUE THREAD

**Issue by lobis** [mipt-npm/gdml.kt#24]
I would be very useful to be able to define groups of physical volumes. At the moment, in order to create multiple instances of a composite physical volume, I am using a `for` loop in the ´world´. 

This works fine when you only need to change the position of the composite volumes, however, if you also need to rotate the composite volume, things get complicated. If you just apply the composite volume rotation to every individual physical volume, then you would also need to rotate the position vector accordingly, which can get messy.

I would be nice to have some kind of object that groups ´physVolume´ objects and that can placed as a physical volume, taking rotation and position parameters, but in this case it handlers the rotation as one would expect, rotating all the child volumes and changing their relative position so that the final result is a rotated composite volume.

Volumes placed with a loop only changing position:
![norotation](https://user-images.githubusercontent.com/35803280/111148646-2d7cc780-858c-11eb-99b8-42dfe81cbf62.JPG)

Same volumes after changing global rotation (but not rotating position)
![rotationY90_nochangeposition](https://user-images.githubusercontent.com/35803280/111148653-2fdf2180-858c-11eb-8bc8-37a2879cdcba.JPG)

**Comment by lobis** [comment]
Here is the expected result of a rotation of 30 degrees:

![rotationGood](https://user-images.githubusercontent.com/35803280/111155062-3e313b80-8594-11eb-8369-edbac857eaa2.JPG)

This was achieved by adding applying a rotation to the relative positions of all physical volumes, I would be thankful if I could avoid doing this in the future.

**Comment by altavir** [comment]
As far as I understand the basic way to do grouping in GDML is to use `assemly`. like that:
```kotlin
        val gdml = Gdml {
            val cube = solids.box(100, 100, 100)
            val air = materials.isotope("G4_AIR")
            structure {
                val cubeVolume = volume(air, cube)
                val group = assembly("group") {
                    repeat(5) { index ->
                        physVolume(cubeVolume) {
                            position { z = index * 100 }
                        }
                    }
                }
                world = assembly("rotated") {
                    physVolume(group) {
                        rotation {
                            x = PI / 4
                        }
                    }
                }
            }
        }
```

I am not sure I can significantly improve this is to allow to place `volume` and `assembly` directly inside the `assembly` block, bypassing the `physVolume` thing.

**Comment by altavir** [comment]
And it would not help since one could attach positions and rotations only to `physVolume`. As I already said, it is a structural problem in GDML design.

**Comment by lobis** [comment]
I have done some tests and I think the `assembly` feature of GDML will be enoughm thanks! Though it is a shame I cannot nest multiple assemblies (or maybe I can?).
![Capture](https://user-images.githubusercontent.com/35803280/111622031-ffe08a00-87e8-11eb-96d8-7a35cb6ca2c3.PNG)

I will close this issue.

**Comment by altavir** [comment]
You can put assembly inside the assembly. The problem with gdml is that there should be physical-logical-physical chain. So you can't put a volume in a volume.

**Comment by lobis** [comment]
> You can put assembly inside the assembly. The problem with gdml is that there should be physical-logical-physical chain. So you can't put a volume in a volume.

Can you tell me explicitly how to do this with the GDML DSL? I can't seem to get it to work. Thanks.

**Comment by altavir** [comment]
Something like this should work:
```kotlin
        val gdml = Gdml {
            val cube = solids.box(100, 100, 100)
            val air = materials.isotope("G4_AIR")
            structure {
                val cubeVolume = volume(air, cube)
                val group = assembly{
                    repeat(5) { index ->
                        physVolume(cubeVolume) {
                            position { z = index * 100 }
                        }
                    }
                }
                val rotated = assembly {
                    physVolume(group) {
                        rotation {
                            x = PI / 4
                        }
                    }                    
                    physVolume(group) {
                        rotation {
                            x = -kotlin.math.PI / 4
                        }
                    }
                }
                world = assembly{
                    physVolume(rotated) {
                        rotation {
                            y = PI / 4
                        }
                    }
                    physVolume(rotated) {
                        rotation {
                            y = -PI / 4
                        }
                    }
                }
            }
        }
 ```

**Comment by lobis** [comment]
> Something like this should work:
> 
> ```kotlin
>         val gdml = Gdml {
>             val cube = solids.box(100, 100, 100)
>             val air = materials.isotope("G4_AIR")
>             structure {
>                 val cubeVolume = volume(air, cube)
>                 val group = assembly{
>                     repeat(5) { index ->
>                         physVolume(cubeVolume) {
>                             position { z = index * 100 }
>                         }
>                     }
>                 }
>                 val rotated = assembly {
>                     physVolume(group) {
>                         rotation {
>                             x = PI / 4
>                         }
>                     }                    
>                     physVolume(group) {
>                         rotation {
>                             x = -kotlin.math.PI / 4
>                         }
>                     }
>                 }
>                 world = assembly{
>                     physVolume(rotated) {
>                         rotation {
>                             y = PI / 4
>                         }
>                     }
>                     physVolume(rotated) {
>                         rotation {
>                             y = -PI / 4
>                         }
>                     }
>                 }
>             }
>         }
> ```

Thanks.
