### ISSUE TITLE
Error parsing materials XML

### ISSUE THREAD

**Issue by lobis** [mipt-npm/gdml.kt#29]
This is probably some silly mistake but I think this XML is correct, yet it gives an error when being parsed via `    loadMaterialsFromUrl("https://raw.githubusercontent.com/rest-for-physics/materials/d7b68502d6d7812a084d49f979ad833a036773e3/materials.xml")`.

https://github.com/rest-for-physics/materials/blob/d7b68502d6d7812a084d49f979ad833a036773e3/materials.xml

```
Caused by: nl.adaptivity.xmlutil.XmlException: Failure to parse children into string at [row,col {unknown-source}]: [9,9]
```

What is wrong with my XML? Thanks.

**Comment by altavir** [comment]
Version 0.0.2 is not allowed for XML header. It is not version of the file, but the version of XML itself. You should use gdml versioning. I have a different error and it is quite obvious from it. After changing the version to 1.0, everything works fine.

**Comment by lobis** [comment]
Thanks, I will change this and implement gdml versioning.
