### ISSUE TITLE
Change materials position in .gdml file for ROOT compatibility

### ISSUE THREAD

**Issue by lobis** [mipt-npm/gdml.kt#38]
As of version `0.4.0-dev-3` the `<materials/>` xml child containing all materials definitions appears at the bottom of the exported .gdml file. This is a problem when visualizing the geometry via the ROOT `TGeoManager` since it will ignore the materials and everything will appear colorless, unless the materials appear at the top.

The decision to place the materials at the end makes the most sense otherwise, it increases the readability. Including the whole `materials.xml` file right at the beginning can be a bit annoying, I suggest implementing an optional parameter to the `loadMaterialsFromUrl` method that when specified, copies only the materials actually referenced in the geometry (and all its components), this would greatly reduce the visual clutter (but may present problems with versioning the materials, that's why we should keep the option to just copy the whole file).

**Comment by altavir** [comment]
It should be fixed in 0.4.0-dev-4 and later

**Comment by lobis** [comment]
I just tested it in `0.4.0-dev-6`. The materials are placed according to the issue but there seems to be a new bug. In the case of my geometry a `GdmlRef` tag appears at the end of the file, which is incompatible with the schema. Here are the last 6 lines of the generated gdml:

```
...
    </structure>
    <setup name="Default" version="1.0">
        <world ref="world"/>
    </setup>
    <GdmlRef ref="G4_Galactic"/>
</gdml>
```

And here is the output after opening it with root:

```
root [0] TGeoManager::Import("BabyIAXO.gdml")
Info in <TGeoManager::Import>: Reading geometry from file: BabyIAXO.gdml
Info in <TGeoManager::TGeoManager>: Geometry GDMLImport, Geometry imported from GDML created
Error: Unsupported GDML Tag Used :GdmlRef. Please Check Geometry/Schema.
Info in <TGeoManager::SetTopVolume>: Top volume is world. Master volume is world
Info in <TGeoNavigator::BuildCache>: --- Maximum geometry depth set to 100
Info in <TGeoManager::CheckGeometry>: Fixing runtime shapes...
Info in <TGeoManager::CheckGeometry>: ...Nothing to fix
Info in <TGeoManager::CloseGeometry>: Counting nodes...
Info in <TGeoManager::Voxelize>: Voxelizing...
Info in <TGeoManager::CloseGeometry>: Building cache...
Info in <TGeoManager::CountLevels>: max level = 3, max placements = 21
Info in <TGeoManager::CloseGeometry>: 468 nodes/ 108 volume UID's in Geometry imported from GDML
Info in <TGeoManager::CloseGeometry>: ----------------modeler ready----------------
(TGeoManager *) 0x562a5a41dd30
```

As you can see, it complains about this `GdmlRef` tag.

After manually removing this tag from the gdml, the geometry seems to be working as intended.

**Comment by altavir** [comment]
Oops. I forgot to add transient tag. Will fix in a moment.

**Comment by altavir** [comment]
Fixed in -dev-7
