### ISSUE TITLE
`World` should not be used in generator

### ISSUE THREAD

**Issue by altavir** [mipt-npm/gdml.kt#6]
Probably it is better to remove the automatic definition of `world` as the first volume in structure because it could confuse things. See the example in #5 .

**Comment by Zelenyy** [comment]
>Probably it is better to remove the automatic definition of world as the first volume in structure because it could confuse things.

Yes, isn't correct. Proposal set `setup.world="world"` as default and raise exception, if volume with this name don't exist.

**Comment by altavir** [comment]
fixed in cfc7fd2
